### ISSUE TITLE
Pokemon X and Y Firmware Update Needed!!! 

### ISSUE THREAD

**Issue by flippinpnoi** [Thulinma/ndsplus#14] opened 2013-10-16 02:09 UTC
Pokemon X and Y are not compatible with firmware 3.05. Please upload a new firmware update as soon as possible! I only bought this hardware for the sole purpose of backing up my save files and I was very disappointed that it does not support my newly bought Pokemon X.

**Comment by Thulinma** [comment] 2013-10-16 07:47
I'm just a user myself here - and I completely agree.
I'm sure EMS already knows about this - I'll update the software with firmware-updating capabilities as soon as they release a new firmware.

**Comment by Thulinma** [comment] 2013-10-16 11:08
Duplicate of #13

**Closed as completed by Thulinma** 2013-10-16 11:08 UTC
